version: '3.4'
services:
  db:
    image: jnsousa/mysql-rest-with-spring-boot-udemy
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_spring_boot_udemy
    ports:
      - 3308:3306
    networks: 
      - udemy-networks
  rest-with-spring-boot-udemy:
    image: jnsousa/rest-with-spring-boot-udemy
    restart: always
    build: ./RestWithSpringBootUdemyJns
    working_dir: /RestWithSpringBootUdemyJns
    environment: 
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes: 
      - ./RestWithSpringBootUdemyJns:/RestWithSpringBootUdemyJns
      - ~/.m2:/root/.m2
    ports: 
      - 8080:8080
    command: mvn clean spring-boot:run
    links: 
      - db
    depends_on: 
      - db
    networks: 
      - udemy-networks
networks:
    udemy-networks:
        driver: bridge    